- hosts: localhost
  tasks:
    - name: install zoom updater
      copy:
        src: zoom-update.service
        dest: /etc/systemd/system
      become: yes
    - name: install zoom update timer
      copy:
        src: zoom-update.timer
        dest: /etc/systemd/system
      become: yes
    - name: enable zoom update timer
      systemd:
        name: zoom-update.timer
        state: started
        enabled: yes
